services:
  buggybot:
    image: baboucheone/buggybot:latest
    container_name: buggybot
    env_file:
      - .env.prod
    ports:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./logs:/buggybot/log
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - HOST_IP=host.docker.internal
    restart: always
